name: setup-azureservicebus-action
description: Set up an Azure Service Bus for testing
inputs:
  connection-string-name:
    description: The name of the environment variable to fill with the Azure Service Bus connection string
    required: true
  azure-credentials:
    description: The JSON blob containing the Azure login credentials. Required setting up the RBAC assignments.
    required: true
  tag:
    description: The name of the component Azure Service Bus is being used for. The Service Bus namespace is tagged with this value.
    required: true
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
